// Datei: widgets\contents\songlangs.dart
const Map<String, String> songLangMap = {
'english':                      '📀',
'american':                     '🇺🇸',
'aave':                         '✊🏿',
'british':                      '🇬🇧',
'jamaican':                     '🇯🇲',
'spanish':                      '🇪🇸',
'portuguese':                   '🇵🇹',
'french':                       '🇫🇷',
'italian':                      '🇮🇹',
'german':                       '🇩🇪',
'korean':                       '🇰🇷',
'arabic':                       '🇸🇦',
'japanese':                     '🇯🇵',
'russian':                      '🇷🇺',
'chinese':                      '🇨🇳',
'tibetan':                      '🛕',
'indian':                       '🇮🇳',
'kiswahili':                    '🇰🇪',
'zulu':                         '🇿🇦',
'fulani':                       '🇳🇬',
'amharic':                      '🇪🇹',
'angolan':                      '🇦🇴',
'baoulé':                       '🇨🇮',
'akan-twi':                     '🇬🇭',
'amazigh':                      '🇲🇦',
'berber':                       '🇩🇿',
'coptic':                       '🇪🇬',
'hebrew':                       '🇮🇱',
'aramaic':                      '🇸🇾',
'sumerian':                     '🇮🇶',
'turkish':                      '🇹🇷',
'phoenician':                   '🇱🇧',
'persian':                      '🇮🇷',
'dutch':                        '🇳🇱',
'austrian':                     '🇦🇹',
'swiss':                        '🇨🇭',
'flemish':                      '🇧🇪',
'polish':                       '🇵🇱',
'czech':                        '🇨🇿',
'belarussian':                  '🇧🇾',
'ukrainian':                    '🇺🇦',
'greek':                        '🇬🇷',
'slovakian':                    '🇸🇰',
'slovenian':                    '🇸🇮',
'hungarian':                    '🇭🇺',
'croatian':                     '🇭🇷',
'serbian':                      '🇷🇸',
'bosnian':                      '🇧🇦',
'romanian':                     '🇷🇴',
'bulgarian':                    '🇧🇬',
'albanian':                     '🇦🇱',
'swedish':                      '🇸🇪',
'norwegian':                    '🇳🇴',
'denish':                       '🇩🇰',
'finnish':                      '🇫🇮',
'icelandic':                    '🇮🇸',
'inuktitut':                    '🇨🇦',
'kalaallisut':                  '🇬🇱',
'thai':                         '🇹🇭',
'filipino':                     '🇵🇭',
'indonesian':                   '🇮🇩',
'malay':                        '🇲🇾',
'vietnamesian':                 '🇻🇳',
'hawaian':                      '🏝️',
'tahitian':                     '🇵🇫',
'niuean':                       '🇳🇺',
'fijian':                       '🇫🇯',
'tokelauan':                    '🇹🇰',
'australian':                   '🇦🇺',
'tongan':                       '🇹🇴',
'māori':                        '🇳🇿',
'bislama':                      '🇻🇺',
'samoan':                       '🇼🇸',
'quechua':                      '🇵🇪',
'guarani':                      '🇵🇾',
'nahuatl':                      '🇲🇽',
'huni-kuin':                    '🇧🇷',
'cherokee':                     '🦅',
'lakota':                       '🐺',
'navajo':                       '🦬',
'irish':                        '🇮🇪',
'old-english':                  '🏰',
'welsh':                        '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
'scottish':                     '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
'archaic-latin':                '🏛️',
'reverse-archaic-latin':        '😈',
'gregorian':                    '⛪',
'ancient-egyptian':             '🔆',
'meow':                         '😺',
'meow-meow':                    '😻',
'esperanto':                    '🌍',
'robot':                        '🤖',
'gen-z':                        '🙄',
'crypto':                       '🚀',
'gibberish':                    '🤪',
'klingon':                      '🖖',
'random':                       '🎲',
};


final List<String> songlangLabels = songLangMap.keys
    .map((k) => _capitalizeDashed(k))
    .toList();

String _capitalizeDashed(String input) {
  return input
      .split('-')
      .map((part) =>
          part.isNotEmpty ? '${part[0].toUpperCase()}${part.substring(1)}' : '')
      .join('-');
}


